api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'api'
urlpatterns = [
    path('', views.api_root),
    path('issues/', views.IssueList.as_view(), name='issue-list'),
    path('issue/<int:pk>/', views.IssueDetail.as_view(), name='issue-detail'),
    path('issue/<int:issue_pk>/progress/', views.ProgressList.as_view(), name='progress-list'),
    path('issue/<int:issue_pk>/progress/<int:pk>/', views.ProgressDetail.as_view(), name='progress-detail'),
    path('comments/', views.CommentList.as_view(), name='comment-list'),
    path('comment/<int:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
    path('users/', views.UserList.as_view(), name='user-list'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),
    path('groups/', views.GroupList.as_view(), name='group-list'),
    path('group/<int:pk>/', views.GroupDetail.as_view(), name='group-detail'),
    path('documents/', views.DocumentList.as_view(), name='document-list'),
    path('document/<int:pk>/', views.DocumentDetail.as_view(), name='document-detail'),
    path('links/', views.LinkList.as_view(), name='link-list'),
    path('link/<int:pk>/', views.LinkDetail.as_view(), name='link-detail'),
    path('categories/', views.CategoryList.as_view(), name='category-list'),
    path('category/<int:pk>/', views.CategoryDetail.as_view(), name='category-detail'),
    path('subcategories/', views.SubCategoryList.as_view(), name='subcategory-list'),
    path('subcategory/<int:pk>/', views.SubCategoryDetail.as_view(), name='subcategory-detail'),
    path('reasons/', views.ReasonList.as_view(), name='reason-list'),
    path('reason/<int:pk>/', views.ReasonDetail.as_view(), name='reason-detail'),
    path('status/', views.StatusList.as_view(), name='status-list'),
    path('status/<int:pk>/', views.StatusDetail.as_view(), name='status-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

issue/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

app_name = 'issue'
urlpatterns = [
    path('', IssueListView.as_view(), name='home'),
    path('create/', IssueCreateView.as_view(), name='createIssue'),
    path('update/<int:pk>/', IssueUpdateView.as_view(), name='updateIssue'),
]

student_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import logout_view, login_view
from issue.views import IssueListView

urlpatterns = [
    path('login/', login_view.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('', IssueListView.as_view(), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('issue/', include('issue.urls')),
    path('support/', include('support.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

issue/models.py
from django.db import models
from django.contrib.auth.models import Group, GroupManager
from account.models import User
from .managers import OpenIssueManager, ClosedIssueManager, DeletedIssueManager
from .mixins import GetterMixin

class Document(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file = models.FileField()

    def __str__(self):
        return f'{self.file.name}'

class Link(models.Model):
    url = models.SlugField(max_length=255)
    anchortext = models.CharField(max_length=32)
    summary = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.anchortext}'

class Category(models.Model, GetterMixin):
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return f'{self.name}'
    
    class Meta:
        verbose_name_plural = "Categories"
        ordering = ['id']

class MyGroup(Group, GetterMixin):
    objects = GroupManager()
    class Meta:
        proxy = True

class SubCategory(models.Model, GetterMixin):
    def default_supported_by():
        return Group.objects.first().id
    name = models.CharField(max_length=32)
    category = models.ForeignKey(Category, related_name='subcategories', default=Category.GeneralId, on_delete=models.SET_DEFAULT)
    supportedBy = models.ForeignKey(Group, related_name='support_categories', default=MyGroup.Level1Id, on_delete=models.SET_DEFAULT)
    links = models.ManyToManyField(Link, blank=True)
    documents = models.ManyToManyField(Document, blank=True)

    def __str__(self):
        return f'{self.category.name} - {self.name}'

    class Meta:
        verbose_name_plural = "SubCategories"
        ordering = ['id']

class Status(models.Model, GetterMixin):
    name = models.CharField(max_length=32, default="New")
    
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = "Statuses"
        ordering = ['id']

class Issue(models.Model):
    def default_status():
        return Status.objects.first().id
    def default_subcategory():
        return SubCategory.objects.first().id
    brief = models.CharField(max_length=128, default="")
    description = models.TextField(default="")
    student = models.ForeignKey(User, related_name='issues', on_delete=models.PROTECT)
    subcategory = models.ForeignKey(SubCategory, default=SubCategory.GeneralId, on_delete=models.PROTECT)
    status = models.ForeignKey(Status, default=Status.NewId, on_delete=models.PROTECT)
    escalation = models.ForeignKey(Group, default=MyGroup.Level1Id, on_delete=models.SET_DEFAULT)

    objects = models.Manager()
    openIssues = OpenIssueManager()
    closedIssues = ClosedIssueManager()
    deletedIssues = DeletedIssueManager()

    def __str__(self):
        return f'{self.student.name} - {self.brief}'
    
    def get_current_progress(self):
        return self.progress.filter(active=1).last()

    def get_current_subcategory(self):
        currentProgress = self.get_current_progress()
        if currentProgress and currentProgress.team:
            return currentProgress.team.name
        else: return None
    
    def get_current_team(self):
        currentProgress = self.get_current_progress()
        if currentProgress and currentProgress.team:
            return currentProgress.team.name
        else: return None
    
    def get_current_assignee(self):
        currentProgress = self.get_current_progress()
        if currentProgress and currentProgress.assignee:
            return currentProgress.assignee.name
        else: return None
    
    def get_current_due(self):
        if currentProgress := self.get_current_progress():
            return currentProgress.due

class Reason(models.Model, GetterMixin):
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return f'{self.name}'
    
class Progress(models.Model):
    assignee = models.ForeignKey(User, null=True, blank=True, default=None, related_name="assigned_tickets", on_delete=models.CASCADE)
    team = models.ForeignKey(Group, default=MyGroup.GeneralId, on_delete=models.SET_DEFAULT)
    issue = models.ForeignKey(Issue, related_name='progress', on_delete=models.CASCADE)
    reason = models.ForeignKey(Reason, null=True, default=Reason.CreatedId, on_delete=models.SET_NULL)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    due = models.DateTimeField(null=True, blank=True)
    closedby = models.ForeignKey(User, related_name="tickets_closed", null=True, blank=True, on_delete=models.SET_NULL)
    finishedDate = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f'Issue {self.issue.id} | pid: {self.id} | {self.reason.name}'
    
    class Meta:
        verbose_name_plural = "Progress"
        ordering = ['issue']


class Comment(models.Model):
    message = models.TextField(blank=True, null=True)
    progress = models.ForeignKey(Progress, related_name='comments', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    link = models.ManyToManyField(Link, blank=True)
    document = models.ManyToManyField(Document, blank=True)

    def __str__(self):
        return f'Issue {self.progress.issue.id}: {self.reason.name}'

issue/forms.py
from django import forms

from .models import Issue

class CreateIssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['brief','description','subcategory','escalation']
        widgets = {
            'brief': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-select'}),
            'escalation': forms.HiddenInput(attrs={'readonly': 'readonly'}),
        }

class UpdateIssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['brief','description','subcategory','student']
        widgets = {
            'brief': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-select'}),
            'student': forms.HiddenInput(attrs={'readonly': 'readonly'}),
        }

api/views/issues_views.py
from rest_framework import generics, status
from rest_framework.response import Response

from api.permissions import IsReportingStudentOrStaff
from api.serializers import IssueSerializer
from issue.models import Issue, Progress


class IssueList(generics.ListCreateAPIView):
    queryset = Issue.objects.all()
    serializer_class = IssueSerializer
    permission_classes = [IsReportingStudentOrStaff]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        newProgress = Progress.objects.create(issue=serializer.instance,
            description="Hello, your ticket is pending assignment to an agent.")
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def get_queryset(self):
        """ 
        If user doesn't have non-Student role, filter list
        to show only tickets reported by themselves
        """
        queryset = Issue.objects.exclude(status__name="Closed").prefetch_related("progress")
        if not self.request.user.is_support_agent():
            queryset = queryset.filter(student=self.request.user).prefetch_related("progress")
        return queryset
    
    def perform_create(self, serializer):
        """ 
        Default "reported by" to logged in user for new issues
        and create first progress reason "created"
        """
        serializer.save(student=self.request.user)

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = IssueSerializer(queryset, many=True, context={'request': request})
        return Response(serializer.data)

class IssueDetail(generics.RetrieveUpdateAPIView):
    queryset = Issue.objects.all()
    serializer_class = IssueSerializer
    permission_classes = [IsReportingStudentOrStaff]

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

issue/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import CreateIssueForm, UpdateIssueForm
from .models import Issue, MyGroup, Status

class IssueListView(LoginRequiredMixin, ListView):
    model = Issue
    paginate_by = 50

    def get_queryset(self):
        """ Return filtered list of issues for student or agent """
        #revert back to 3.9 compat, as django docker-compose is v3.9 LS
        view = self.request.user.active_view
        if view == 'Open': qs = Issue.openIssues.all()
        if view == 'New': qs = Issue.openIssues.filter(status__name='New')
        if view == 'Assigned': qs = Issue.objects.filter(status__name='Assigned')
        if view == 'In Progress': qs = Issue.objects.filter(status__name='In Progress')
        if view == 'Blocked': qs = Issue.objects.filter(status__name='Blocked')
        if view == 'Referred': qs = Issue.objects.filter(status__name='Referred')
        if view == 'Escalated': qs = Issue.objects.filter(escalation__name__in=['Level2','Level3'])
        if view == 'Resolved': qs = Issue.objects.filter(status__name='Resolved')
        if view == 'Closed': qs = Issue.closedIssues.all()
        if view == 'Deleted': qs = Issue.objects.filter(status__name='Deleted')
        if not self.request.user.is_support_agent():
            qs = qs.filter(student=self.request.user)
        return qs

    def get(self, request, *args, **kwargs):
        request.user.active_view = request.GET.get('filter','Open')
        request.user.save()
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(
                self.object_list, "exists"
            ):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                raise Http404(
                    _("Empty list and “%(class_name)s.allow_empty” is False.")
                    % {
                        "class_name": self.__class__.__name__,
                    }
                )
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['createIssueForm'] = CreateIssueForm
        context['updateIssueForm'] = UpdateIssueForm
        context['applied_filter'] = self.request.GET.get('filter', 'Open')
        context['statuses'] = Status.objects.all()
        return context

class IssueCreateView(LoginRequiredMixin, CreateView):
    success_message = "Your issue was added, we'll be in touch soon."
    success_url = reverse_lazy('issue:home')
    form_class = CreateIssueForm
    template_name = 'issue/issue_list.html'
    model = Issue

    def form_valid(self, form, request):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.student = request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        
        if form.is_valid():
            return self.form_valid(form, request)
        else:
            return self.form_invalid(form)
        
class IssueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    success_url = reverse_lazy('issue:home')
    form_class = UpdateIssueForm
    template_name = 'issue/issue_update_form.html'
    model = Issue

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        submitButtons = ['Update','Escalate','Resolve','Close']
        btn = [btn for btn in submitButtons if btn in request.POST][0]

        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, btn)
        return self.form_invalid(form)

    def test_func(self):
        obj = self.get_object()
        staff = bool(self.request.user.is_support_agent())
        myself = bool(obj.student == self.request.user)
        safe = bool(self.request.method == 'GET' or 
                    'Escalate' not in self.request.POST)
        return staff or (myself and safe)
    
    def form_valid(self, form, btn):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        if btn == 'Escalate':
            if self.object.escalation_id == MyGroup.Level1Id():
                self.object.escalation_id = MyGroup.Level2Id()
            else:
                self.object.escalation_id = MyGroup.Level3Id()
        if btn == 'Resolve':
            self.object.status_id = Status.ResolvedId()
        if btn == 'Closed':
            self.object.status_id = Status.ClosedId()
        self.object.save()
        return super().form_valid(form)

issue/templates/issue/document_form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Uploaded at</th>
        <th>Size</th>
      </tr>
    </thead>
    <tbody>
      {% for document in documents %}
        <tr>
          <td><a href="{{ document.file.url }}" target="_blank">{{ document.file.name }}</a></td>
          <td>{{ document.uploaded_at }}</td>
          <td>{{ document.file.size|filesizeformat }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No data.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

issue/templates/issue/issue_create_modal.html
<div class="modal fade" id="newIssue" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
aria-labelledby="newIssueLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title fs-5" id="newIssueLabel">Submit a New Issue</h2>
        </div>
        <form method="post" action="{% url 'issue:createIssue' %}">{% csrf_token %}
            <div class="modal-body">
                {{ createIssueForm.as_p }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success">Create</button>
            </div>
        </form>
    </div>
</div>
</div>

issue/templates/issue/issue_list.html
{% extends "base.html" %}
{% block content %}

{% include 'issuelist-sidebar.html' %}
<div class="col-md-10 d-none d-md-block bg-light sidebar border border-secondary rounded-end"
    style="--bs-border-opacity: .3;">
    <header class="d-flex justify-content-between my-5 border-bottom" style="min-height: 80px;">
        <div class="left">
            <h2>{{ applied_filter }} Issues</h2>
            <h5>{{issue_list.count}} issues</h5>
        </div>
    </header>
    {% if issue_list %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"><input class="form-check-input mt-0" type="checkbox" value="" aria-label="Checkbox for select-all"></th>
                <th scope="col"></th>
                <th scope="col">Brief</th>
                <th scope="col">Category</th>
                <th scope="col">Team</th>
                <th scope="col">Assignee</th>
                <th scope="col">Due</th>
                <th scope="col">Status</th>
                <th scope="col">Escalation</th>
            </tr>
        </thead>
        <tbody>
            {% for issue in issue_list %}
            <tr>
              <th scope="row"><input class="form-check-input mt-0" type="checkbox" value="" aria-label="Checkbox for issue {{issue.pk}}"></th>
              <td><button type="button" class="btn btn-sm btn-secondary" data-bs-toggle="modal" data-bs-target="#updateIssue" data-bs-issuepk="{{issue.pk}}">Open</button>
              </td>
              <td>{{ issue.brief }}</td>
              <td>{{ issue.subcategory.name }}</td>
              <td>{{ issue.get_current_team }}</td>
              <td>{{ issue.get_current_assignee }}</td>
              <td>{{ issue.get_current_due }}</td>
              <td>{{ issue.status }}</td>
              <td>{{ issue.escalation.name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </table>
    {% else %}
    <p class="text-muted">You do not have any {{ applied_filter }} issues.</p>
    {% endif %}
</div>
{% include 'issue/issue_create_modal.html' %}
{% include 'issue/issue_update_modal.html' %}
{% endblock %}

issue/templates/issue/issue_update.html
{{ form.as_p }}

issue/templates/issue/issue_update_form.html
{{ form.as_p }}

issue/templates/issue/issue_update_modal.html
<div class="modal fade" id="updateIssue" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
aria-labelledby="updateIssueLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title fs-5" id="updateIssueLabel">Update an Issue</h2>
        </div>
        <form method="post" action="">{% csrf_token %}
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" name = "Update" class="btn btn-success">Update</button>
                {% if user.is_support_agent %}
                <button type="submit" name = "Escalate" class="btn btn-warning">Escalate</button>
                <button type="submit" name = "Resolve" class="btn btn-info">Resolve</button>
                <button type="submit" name = "Close" class="btn btn-outline-danger">Close</button>
                {% endif %}
            </div>
        </form>
    </div>
</div>
</div>