api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'api'
urlpatterns = [
    path('', views.api_root),
    path('issues/', views.IssueList.as_view(), name='issue-list'),
    path('issue/<int:pk>/', views.IssueDetail.as_view(), name='issue-detail'),
    path('issue/<int:issue_pk>/progress/', views.ProgressList.as_view(), name='progress-list'),
    path('issue/<int:issue_pk>/progress/<int:pk>/', views.ProgressDetail.as_view(), name='progress-detail'),
    path('comments/', views.CommentList.as_view(), name='comment-list'),
    path('comment/<int:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
    path('users/', views.UserList.as_view(), name='user-list'),
    path('user/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),
    path('groups/', views.GroupList.as_view(), name='group-list'),
    path('group/<int:pk>/', views.GroupDetail.as_view(), name='group-detail'),
    path('documents/', views.DocumentList.as_view(), name='document-list'),
    path('document/<int:pk>/', views.DocumentDetail.as_view(), name='document-detail'),
    path('links/', views.LinkList.as_view(), name='link-list'),
    path('link/<int:pk>/', views.LinkDetail.as_view(), name='link-detail'),
    path('categories/', views.CategoryList.as_view(), name='category-list'),
    path('category/<int:pk>/', views.CategoryDetail.as_view(), name='category-detail'),
    path('subcategories/', views.SubCategoryList.as_view(), name='subcategory-list'),
    path('subcategory/<int:pk>/', views.SubCategoryDetail.as_view(), name='subcategory-detail'),
    path('reasons/', views.ReasonList.as_view(), name='reason-list'),
    path('reason/<int:pk>/', views.ReasonDetail.as_view(), name='reason-detail'),
    path('status/', views.StatusList.as_view(), name='status-list'),
    path('status/<int:pk>/', views.StatusDetail.as_view(), name='status-detail'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

issue/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

app_name = 'issue'
urlpatterns = [
    path('', IssueListView.as_view(), name='home'),
    path('create/', IssueCreateView.as_view(), name='createIssue'),
    path('update/<int:pk>/', IssueUpdateView.as_view(), name='updateIssue'),
]

student_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import logout_view, login_view
from issue.views import IssueListView

urlpatterns = [
    path('login/', login_view.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('', IssueListView.as_view(), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('issue/', include('issue.urls')),
    path('support/', include('support.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Student Tracker{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'issue/css/main.css' %}">
</head>

<body class="bg-tirtiary bg-gradient">
    {% include 'topnav.html' %}
    <div class="container-fluid m-1">
        <div class="row" style="min-height: calc(100vh - 100px)!important; margin-right:-4px!important">
            {% if user.is_superuser %}
            {% include 'sidebar.html' %}
            {% endif %}
            <main class="col-md-{{user.main_cols}} rounded" style="padding:0!important">
                <div class="container-fluid">
                    <div class="row" style="min-height: calc(100vh - 100px)!important; margin-right:-6px!important">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="{% static 'issue/js/issue.js' %}"></script>
</body>

</html>

templates/issuelist-sidebar.html
<nav class="col-md-2 d-none d-md-block bg-body-tertiary" id="issuelist_sidebar">
    <div class="sidebar-sticky">
        <header class="my-3 border-bottom d-flex flex-column align-content-end">
            <button class="btn btn-success mb-5" data-bs-toggle="modal" data-bs-target="#newIssue">Add New Ticket</button>
            <h2 class="text-muted">Views</h2>
        </header>
        <ul class="nav d-flex flex-column">
            {% if user.is_support_agent %}
            {% else %}
            {% endif %}
            <li class="{% if user.active_view == 'Open' %}active{% endif %} nav-item rounded shadow">
                <a class="text-decoration-none text-muted" href="{% url 'issue:home' %}">All Open Tickets</a>
            </li>
            {% for status in statuses %}
            <li class="{% if user.active_view == status.name %}active{% endif %} nav-item rounded shadow {{status}}">
                <a class="text-decoration-none text-muted {{status}}" href="{% url 'issue:home' %}?filter={{status}}">{{status}} Tickets</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</nav> 

templates/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-body-secondary rounded-start">
<div class="sidebar-sticky">
        <header class="my-5 d-flex align-items-end" style="min-height: 80px;"></header>
        <ul class="nav d-flex flex-column">
            <li class="nav-item">
                <a class="nav-link text-secondary active" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-secondary" href="#">Reports</a>
            </li>
            <li class="nav-item flex-grow-1">
                <a class="nav-link text-secondary" href="#">Analytics</a>
            </li>
        </ul>
    </div>
</nav>

templates/topnav.html
<nav class="navbar navbar-expand-lg bg-dark m-1 border border-secondary rounded" style="--bs-border-opacity: .3;"
    data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white fw-bold fs-1" href="#">Student Issue Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav text-light">
                <li class="nav-item">Welcome,<br/>{% if user.name %}{{user.name}}{% else %}{{user.email}}{% endif %}</li>
                <li class="nav-item d-flex align-items-center justify-content-center mx-5 text-light">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                        class="bi bi-bell" viewBox="0 0 16 16">
                        <path
                            d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z" />
                    </svg>
                </li>
                <li class="nav-item">
                    <div class="dropdown p-0">
                        <a href="#"
                            class="d-flex align-items-center justify-content-center text-decoration-none text-light dropdown-toggle"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                                viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z" />
                                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                            </svg>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end pull-left text-small shadow">
                            <!-- <li><a class="dropdown-item" href="#">Admin</a></li> -->
                            <!-- <li><hr class="dropdown-divider"></li> -->
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>